import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import TableDataAPI from './components/TableDataAPI'
import InputLastLetter from './components/InputLastLetter'
import DetectedConsonant from './components/DetectedConsonant'
import WordsCounter from './components/WordsCounter'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <TableDataAPI></TableDataAPI>
        <br></br>
        <InputLastLetter></InputLastLetter>
        <br></br>
        <DetectedConsonant></DetectedConsonant>
        <br></br>
        <WordsCounter></WordsCounter>
      </main>
    </>
  )
}
